export const validCoreProfileFieldNames = [
    "character_name",
    "char_class",
    "race",
    "proficiency",
    "char_level",
    "experience",
    "next_level",
    "affinity",
]

export const validCombatStatsFieldNames = [
    "current_hp",
    "max_hp",
    "temp_hp",
    "armor_class",
    "hit_dice",
    "max_hit_dice",
    "speed",
    "initiative",
    "inspiration",
    "spell_casting",
    "spell_save",
    "spell_attack",
]

export const validAbilityScoresFieldNames = [
    "str_score",
    "dex_score",
    "con_score",
    "int_score",
    "wis_score",
    "chr_score",
    "str_mod",
    "dex_mod",
    "con_mod",
    "int_mod",
    "wis_mod",
    "chr_mod",
    "str_save",
    "dex_save",
    "con_save",
    "int_save",
    "wis_save",
    "chr_save",
    "passive_perception",
]

export const validBackgroundFieldNames = [
    "personality",
    "backstory",
    "bonds",
    "appearance",
    "ideals",
    "flaws",
    "valuables",
    "additional_traits",
]

export const validFeatsTraitsFieldNames = [
    "feats_traits",
    "weapon_proficiency",
    "armor_proficiency",
    "buffs",
    "debuffs",
    "other_proficiency",
]

export const validExplorationSkillsFieldNames = [
    "acrobatics",
    "animal",
    "arcana",
    "athletics",
    "deception",
    "history",
    "insight",
    "intimidation",
    "investigation",
    "medicine",
    "nature",
    "perception",
    "performance",
    "persuasion",
    "religion",
    "sleight",
    "stealth",
    "survival",
  ];

  export const validSpellSlotsFieldNames = [
    "first_available",
    "first_max",
    "second_available",
    "second_max",
    "third_available",
    "third_max",
    "fourth_available",
    "fourth_max",
    "fifth_available",
    "fifth_max",
    "sixth_available",
    "sixth_max",
    "seventh_available",
    "seventh_max",
    "eighth_available",
    "eighth_max",
    "nineth_available",
    "nineth_max",
  ];
  